version: "3.9"
services:
  api:
    image: duda-demo-api
    environment:
      PG_HOST: postgres
    ports:
      - "8090:8090"

  postgres:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: duda

    #ports:
    #  - "15432:5432"
